### PR TITLE
Handling errors on cd-metrics

### LINKED ISSUE #87: Cd-Metrics API errors should fail gracefully and not take down the client

### PR DESCRIPTION
**Pull request by andrenatal**
Fixes #87 

@kdavis-mozilla I was able to reproduce your issue on my end when I start the client with no network connection, and with this patch the client isn't crashing anymore. Please let me know if lgty.

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
It looks good to me, but I'm going to run the patch today before merging to make sure we didn't miss anything.

**Comment by kdavis-mozilla** [comment]
Looks like it works, but I want to let it run longer. Now instead of causing a re-start it yields the log message 

```
...
Aug 23 06:39:10 vaani node[810]: Caught error on cd-metrics { [Error: getaddrinfo ENOTFOUND www.google-analytics.com www.google-analytics.com:443]
Aug 23 06:39:10 vaani node[810]: code: 'ENOTFOUND',
Aug 23 06:39:10 vaani node[810]: errno: 'ENOTFOUND',
Aug 23 06:39:10 vaani node[810]: syscall: 'getaddrinfo',
Aug 23 06:39:10 vaani node[810]: hostname: 'www.google-analytics.com',
Aug 23 06:39:10 vaani node[810]: host: 'www.google-analytics.com',
Aug 23 06:39:10 vaani node[810]: port: '443',
Aug 23 06:39:10 vaani node[810]: domainEmitter:
Aug 23 06:39:10 vaani node[810]: ClientRequest {
Aug 23 06:39:10 vaani node[810]: domain:
Aug 23 06:39:10 vaani node[810]: Domain {
Aug 23 06:39:10 vaani node[810]: domain: null,
Aug 23 06:39:10 vaani node[810]: _events: [Object],
Aug 23 06:39:10 vaani node[810]: _eventsCount: 1,
Aug 23 06:39:10 vaani node[810]: _maxListeners: undefined,
Aug 23 06:39:10 vaani node[810]: members: [] },
Aug 23 06:39:10 vaani node[810]: _events: { response: [Object] },
Aug 23 06:39:10 vaani node[810]: _eventsCount: 1,
Aug 23 06:39:10 vaani node[810]: _maxListeners: undefined,
Aug 23 06:39:10 vaani node[810]: output: [],
Aug 23 06:39:10 vaani node[810]: outputEncodings: [],
Aug 23 06:39:10 vaani node[810]: outputCallbacks: [],
Aug 23 06:39:10 vaani node[810]: outputSize: 0,
Aug 23 06:39:10 vaani node[810]: writable: true,
Aug 23 06:39:10 vaani node[810]: _last: true,
Aug 23 06:39:10 vaani node[810]: chunkedEncoding: false,
Aug 23 06:39:10 vaani node[810]: shouldKeepAlive: false,
Aug 23 06:39:10 vaani node[810]: useChunkedEncodingByDefault: true,
Aug 23 06:39:10 vaani node[810]: sendDate: false,
Aug 23 06:39:10 vaani node[810]: _removedHeader: { 'content-length': false },
Aug 23 06:39:10 vaani node[810]: _contentLength: null,
Aug 23 06:39:10 vaani node[810]: _hasBody: true,
Aug 23 06:39:10 vaani node[810]: _trailer: '',
Aug 23 06:39:10 vaani node[810]: finished: true,
Aug 23 06:39:10 vaani node[810]: _headerSent: true,
Aug 23 06:39:10 vaani node[810]: socket:
Aug 23 06:39:10 vaani node[810]: TLSSocket {
Aug 23 06:39:10 vaani node[810]: _tlsOptions: [Object],
Aug 23 06:39:10 vaani node[810]: _secureEstablished: false,
Aug 23 06:39:10 vaani node[810]: _securePending: false,
Aug 23 06:39:10 vaani node[810]: _newSessionPending: false,
Aug 23 06:39:10 vaani node[810]: _controlReleased: true,
Aug 23 06:39:10 vaani node[810]: _SNICallback: null,
Aug 23 06:39:10 vaani node[810]: servername: null,
Aug 23 06:39:10 vaani node[810]: npnProtocol: null,
Aug 23 06:39:10 vaani node[810]: authorized: false,
Aug 23 06:39:10 vaani node[810]: authorizationError: null,
Aug 23 06:39:10 vaani node[810]: encrypted: true,
Aug 23 06:39:10 vaani node[810]: _events: [Object],
Aug 23 06:39:10 vaani node[810]: _eventsCount: 12,
Aug 23 06:39:10 vaani node[810]: _connecting: true,
Aug 23 06:39:10 vaani node[810]: _hadError: false,
Aug 23 06:39:10 vaani node[810]: _handle: [Object],
Aug 23 06:39:10 vaani node[810]: _parent: null,
Aug 23 06:39:10 vaani node[810]: _host: 'www.google-analytics.com',
Aug 23 06:39:10 vaani node[810]: _readableState: [Object],
Aug 23 06:39:10 vaani node[810]: readable: true,
Aug 23 06:39:10 vaani node[810]: domain: [Object],
Aug 23 06:39:10 vaani node[810]: _maxListeners: undefined,
Aug 23 06:39:10 vaani node[810]: _writableState: [Object],
Aug 23 06:39:10 vaani node[810]: writable: true,
Aug 23 06:39:10 vaani node[810]: allowHalfOpen: false,
Aug 23 06:39:10 vaani node[810]: destroyed: false,
Aug 23 06:39:10 vaani node[810]: _bytesDispatched: 0,
Aug 23 06:39:10 vaani node[810]: _sockname: null,
Aug 23 06:39:10 vaani node[810]: _pendingData: [Object],
Aug 23 06:39:10 vaani node[810]: _pendingEncoding: '',
Aug 23 06:39:10 vaani node[810]: server: undefined,
Aug 23 06:39:10 vaani node[810]: _server: null,
Aug 23 06:39:10 vaani node[810]: ssl: [Object],
Aug 23 06:39:10 vaani node[810]: _requestCert: true,
Aug 23 06:39:10 vaani node[810]: _rejectUnauthorized: true,
Aug 23 06:39:10 vaani node[810]: parser: [Object],
Aug 23 06:39:10 vaani node[810]: _httpMessage: [Circular],
Aug 23 06:39:10 vaani node[810]: read: [Function],
Aug 23 06:39:10 vaani node[810]: _consuming: true },
Aug 23 06:39:10 vaani node[810]: connection:
Aug 23 06:39:10 vaani node[810]: TLSSocket {
Aug 23 06:39:10 vaani node[810]: _tlsOptions: [Object],
Aug 23 06:39:10 vaani node[810]: _secureEstablished: false,
Aug 23 06:39:10 vaani node[810]: _securePending: false,
Aug 23 06:39:10 vaani node[810]: _newSessionPending: false,
Aug 23 06:39:10 vaani node[810]: _controlReleased: true,
Aug 23 06:39:10 vaani node[810]: _SNICallback: null,
Aug 23 06:39:10 vaani node[810]: servername: null,
Aug 23 06:39:10 vaani node[810]: npnProtocol: null,
Aug 23 06:39:10 vaani node[810]: authorized: false,
Aug 23 06:39:10 vaani node[810]: authorizationError: null,
Aug 23 06:39:10 vaani node[810]: encrypted: true,
Aug 23 06:39:10 vaani node[810]: _events: [Object],
Aug 23 06:39:10 vaani node[810]: _eventsCount: 12,
Aug 23 06:39:10 vaani node[810]: _connecting: true,
Aug 23 06:39:10 vaani node[810]: _hadError: false,
Aug 23 06:39:10 vaani node[810]: _handle: [Object],
Aug 23 06:39:10 vaani node[810]: _parent: null,
Aug 23 06:39:10 vaani node[810]: _host: 'www.google-analytics.com',
Aug 23 06:39:10 vaani node[810]: _readableState: [Object],
Aug 23 06:39:10 vaani node[810]: readable: true,
Aug 23 06:39:10 vaani node[810]: domain: [Object],
Aug 23 06:39:10 vaani node[810]: _maxListeners: undefined,
Aug 23 06:39:10 vaani node[810]: _writableState: [Object],
Aug 23 06:39:10 vaani node[810]: writable: true,
Aug 23 06:39:10 vaani node[810]: allowHalfOpen: false,
Aug 23 06:39:10 vaani node[810]: destroyed: false,
Aug 23 06:39:10 vaani node[810]: _bytesDispatched: 0,
Aug 23 06:39:10 vaani node[810]: _sockname: null,
Aug 23 06:39:10 vaani node[810]: _pendingData: [Object],
Aug 23 06:39:10 vaani node[810]: _pendingEncoding: '',
Aug 23 06:39:10 vaani node[810]: server: undefined,
Aug 23 06:39:10 vaani node[810]: _server: null,
Aug 23 06:39:10 vaani node[810]: ssl: [Object],
Aug 23 06:39:10 vaani node[810]: _requestCert: true,
Aug 23 06:39:10 vaani node[810]: _rejectUnauthorized: true,
Aug 23 06:39:10 vaani node[810]: parser: [Object],
Aug 23 06:39:10 vaani node[810]: _httpMessage: [Circular],
Aug 23 06:39:10 vaani node[810]: read: [Function],
Aug 23 06:39:10 vaani node[810]: _consuming: true },
Aug 23 06:39:10 vaani node[810]: _header: 'POST /batch HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 193\r\nHost: www.google-analytics.com\r\nConnection: close\r\n\r\n',
Aug 23 06:39:10 vaani node[810]: _headers:
Aug 23 06:39:10 vaani node[810]: { 'content-type': 'application/x-www-form-urlencoded',
Aug 23 06:39:10 vaani node[810]: 'content-length': 193,
Aug 23 06:39:10 vaani node[810]: host: 'www.google-analytics.com' },
Aug 23 06:39:10 vaani node[810]: _headerNames:
Aug 23 06:39:10 vaani node[810]: { 'content-type': 'Content-Type',
Aug 23 06:39:10 vaani node[810]: 'content-length': 'Content-Length',
Aug 23 06:39:10 vaani node[810]: host: 'Host' },
Aug 23 06:39:10 vaani node[810]: _onPendingData: null,
Aug 23 06:39:10 vaani node[810]: agent:
Aug 23 06:39:10 vaani node[810]: Agent {
Aug 23 06:39:10 vaani node[810]: domain: null,
Aug 23 06:39:10 vaani node[810]: _events: [Object],
Aug 23 06:39:10 vaani node[810]: _eventsCount: 1,
Aug 23 06:39:10 vaani node[810]: _maxListeners: undefined,
Aug 23 06:39:10 vaani node[810]: defaultPort: 443,
Aug 23 06:39:10 vaani node[810]: protocol: 'https:',
Aug 23 06:39:10 vaani node[810]: options: [Object],
Aug 23 06:39:10 vaani node[810]: requests: {},
Aug 23 06:39:10 vaani node[810]: sockets: [Object],
Aug 23 06:39:10 vaani node[810]: freeSockets: {},
Aug 23 06:39:10 vaani node[810]: keepAliveMsecs: 1000,
Aug 23 06:39:10 vaani node[810]: keepAlive: false,
Aug 23 06:39:10 vaani node[810]: maxSockets: Infinity,
Aug 23 06:39:10 vaani node[810]: maxFreeSockets: 256,
Aug 23 06:39:10 vaani node[810]: maxCachedSessions: 100,
Aug 23 06:39:10 vaani node[810]: _sessionCache: [Object] },
Aug 23 06:39:10 vaani node[810]: socketPath: undefined,
Aug 23 06:39:10 vaani node[810]: method: 'POST',
Aug 23 06:39:10 vaani node[810]: path: '/batch',
Aug 23 06:39:10 vaani node[810]: parser:
Aug 23 06:39:10 vaani node[810]: HTTPParser {
Aug 23 06:39:10 vaani node[810]: '0': [Function: parserOnHeaders],
Aug 23 06:39:10 vaani node[810]: '1': [Function: parserOnHeadersComplete],
Aug 23 06:39:10 vaani node[810]: '2': [Function: parserOnBody],
Aug 23 06:39:10 vaani node[810]: '3': [Function: parserOnMessageComplete],
Aug 23 06:39:10 vaani node[810]: '4': null,
Aug 23 06:39:10 vaani node[810]: _headers: [],
Aug 23 06:39:10 vaani node[810]: _url: '',
Aug 23 06:39:10 vaani node[810]: _consumed: false,
Aug 23 06:39:10 vaani node[810]: socket: [Object],
Aug 23 06:39:10 vaani node[810]: incoming: null,
Aug 23 06:39:10 vaani node[810]: outgoing: [Circular],
Aug 23 06:39:10 vaani node[810]: maxHeaderPairs: 2000,
Aug 23 06:39:10 vaani node[810]: onIncoming: [Function: parserOnIncomingClient] } },
Aug 23 06:39:10 vaani node[810]: domain:
Aug 23 06:39:10 vaani node[810]: Domain {
Aug 23 06:39:10 vaani node[810]: domain: null,
Aug 23 06:39:10 vaani node[810]: _events: { error: [Function] },
Aug 23 06:39:10 vaani node[810]: _eventsCount: 1,
Aug 23 06:39:10 vaani node[810]: _maxListeners: undefined,
Aug 23 06:39:10 vaani node[810]: members: [] },
Aug 23 06:39:10 vaani node[810]: domainThrown: false }
...
```

**Comment by andrenatal** [comment]
Yes. Same behavior here. Do you want to remove the log? I think it's
important to leave it.

**Comment by andrenatal** [comment]
I think it's also important to understand why the resolve of
google-analytics domain fails on rpi. If that's an OS underlying issue that
can also affect the resolve of the speech server hostname.

**Comment by kdavis-mozilla** [comment]
I'd say leave the log.

**Comment by kdavis-mozilla** [comment]
LGTM. Merge into master and deployed @andrenatal whenever you're ready.

**Pull request merged**
