### PR TITLE
Two tier configuration handling

### PR DESCRIPTION
**Pull request by tilmankamp**
@andrenatal : This is the two tier config file loading, which was required for having a different audio-device config on the RPi. Please merge/use it, if still needed.

### CODE REVIEW

**Comment by kdavis-mozilla** [comment]
What about servertools.js?

**Comment by tilmankamp** [comment]
Because of this in servertools.js:

``` js
    setup: function(wakeword, config, audiotools, resetlisten, logging){
        this.wakeword = wakeword;
        this.config = config;
        this.audiotools = audiotools;
        this.resetlisten = resetlisten;
        this.logging = logging;
```

The config gets passed in from outside. Didn't want to restructure more code than necessary.
And nobody knows which other overwritings will be necessary. I am anyhow no big fan of this, as having the config in the repo is the actual root problem.

**Comment by kdavis-mozilla** [comment]
I guess I was thinking more about this line...

```
this.secret = JSON.parse(process.env.VAANI_CONFIG || fs.readFileSync("secret.json"));
```

**Comment by tilmankamp** [comment]
I see. It's just the secret - don't know if we should mix it up with the config. `VAANI_CONFIG` is indeed naming wise misleading.

**Comment by kdavis-mozilla** [comment]
I agree. It seemed, and seems, strange to me.

**Pull request merged**
